CREATE TABLE IF NOT EXISTS REVIEWS (
    ID INT UNIQUE,
    IMAGES TEXT, -- JSON
    RATING INT,
    RESTAURANT TEXT, -- MAPS ID
    COMMENTS VARCHAR(500),
    FRY_TYPE VARCHAR(24),
    FRESH INT,      -- 1:FRESH;0:FROZEN
    TOPPINGS INT,   -- 1:TOPPINGS;0:NOT
    SPICED INT,     -- 1:SPICED OTHER THAN SALT;0:NOT SPICED OTHER THAN SALT
    REVIEW_DATE DATETIME,
    REVIEWER INT -- ID
);
CREATE TABLE IF NOT EXISTS IMAGES (
    ID INT UNIQUE,
    LAT FLOAT,
    LON FLOAT,
    TAKEN_DATE DATETIME,
    UPLOAD_DATE DATETIME
);
CREATE TABLE IF NOT EXISTS RESTAURANTS (
    ID TEXT UNIQUE,
    NAME TEXT,
    ADDRESS TEXT,
    THUMBNAIL TEXT, -- PATH
    LAT FLOAT,
    LON FLOAT
);
-- rinchen